// <auto-generated />
namespace Foxtrot.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class adding_indices_to_firstname_and_last_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_indices_to_firstname_and_last_name));
        
        string IMigrationMetadata.Id
        {
            get { return "201410270647008_adding_indices_to_firstname_and_last_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
