// <auto-generated />
namespace Foxtrot.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class adding_search_text_column_to_employee_profile : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_search_text_column_to_employee_profile));
        
        string IMigrationMetadata.Id
        {
            get { return "201410251727153_adding_search_text_column_to_employee_profile"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
